version: '3.8'
services:
  chatbot:
    container_name: 'Chatbot'
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - './default.conf:/etc/nginx/conf.d/default.conf'
